# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macos_build_test:
    name: Build/test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  ios_tests:
    name: Build/test on iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests on iOS
        run: xcodebuild -scheme ColorPaletteCodable test -destination "platform=iOS Simulator,name=iPhone SE (3rd generation),OS=latest"
